const config = {
  TRAX: {
    //*  indicar tipo de reporte, con sus respectivos elementos, la extensión en caracteres
    //*  y la posición en que comienzan.
    RPF: {
      positionDate: { lenght: 6, start: 0, end: 6 },
      positionTime: { lenght: 6, start: 6, end: 12 },
      positionLat: { lenght: 8, start: 12, end: 20 },
      positionLon: { lenght: 8, start: 20, end: 29 },
      speed: { lenght: 3, start: 29, end: 32 },
      direction: { lenght: 3, start: 32, end: 35 },
      positionDimension: { lenght: 1, start: 35, end: 36 },
      age: { lenght: 2, start: 36, end: 38 },
      reportState: { lenght: 2, start: 38, end: 40 },
      reportEvent: { lenght: 2, start: 40, end: 42 },
      msgChars: 69,
    },
    RPG: {
      positionDate: { lenght: 6, start: 0, end: 6 },
      positionTime: { lenght: 6, start: 6, end: 12 },
      positionLat: { lenght: 8, start: 12, end: 20 },
      positionLon: { lenght: 8, start: 20, end: 29 },
      speed: { lenght: 3, start: 29, end: 32 },
      direction: { lenght: 3, start: 32, end: 35 },
      satelitesQuantity: { lenght: 1, start: 35, end: 36 },
      age: { lenght: 2, start: 36, end: 38 },
      reportState: { lenght: 2, start: 38, end: 40 },
      reportEvent: { lenght: 2, start: 40, end: 42 },
    },
  },
  QUECLINK: {
    GTFRI: {
      22: {
        Evento: 1,
        IMEI: 2,
        UID: 3,
        ExternalPower: 4,
        ReportID: 5,
        Speed: 8,
        Heading: 9,
        Altitud: 10,
        Lon: 11,
        Lat: 12,
        GNSSUTC: 13,
        Battery: 19,
        Nro: 21,
      },
      30: {
        Evento: 1,
        IMEI: 2,
        UID: 3,
        ExternalPower: 4,
        ReportID: 5,
        Speed: 8,
        Heading: 9,
        Altitud: 10,
        Lon: 11,
        Lat: 12,
        GNSSUTC: 13,
        Battery: 23,
        Nro: 29,
      },
    },
    GTPNL: {
      Evento: 1,
      IMEI: 2,
      UID: 3,
      ExternalPower: 4,
      ReportID: 5,
      Speed: 8,
      Heading: 9,
      Altitud: 10,
      Lon: 11,
      Lat: 12,
      GNSSUTC: 13,
      Battery: 23,
      Nro: 29,
    },
    GTSOS: {
      Evento: 22,
      IMEI: 2,
      UID: 3,
      ExternalPower: 4,
      ReportID: 5,
      Speed: 8,
      Heading: 9,
      Altitud: 10,
      Lon: 11,
      Lat: 12,
      GNSSUTC: 13,
      Battery: 19,
      Nro: 21,
    },
    GTEPF: {
      Evento: 11,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 5,
      Heading: 6,
      Altitud: 7,
      Lon: 8,
      Lat: 9,
      GNSSUTC: 10,
      Battery: 'SD',
      Nro: 17,
    },
    GTEPN: {
      Evento: 12,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 5,
      Heading: 6,
      Altitud: 7,
      Lon: 8,
      Lat: 9,
      GNSSUTC: 10,
      Battery: 'SD',
      Nro: 17,
    },
    GTBPL: {
      Evento: 23,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 6,
      Heading: 7,
      Altitud: 8,
      Lon: 9,
      Lat: 10,
      GNSSUTC: 11,
      Battery: 'SD',
      Nro: 18,
    },
    GTBTC: {
      Evento: 24,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 5,
      Heading: 6,
      Altitud: 7,
      Lon: 8,
      Lat: 9,
      GNSSUTC: 10,
      Battery: 'SD',
      Nro: 17,
    },
    GTIDN: {
      Evento: 2,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 7,
      Heading: 8,
      Altitud: 9,
      Lon: 10,
      Lat: 11,
      GNSSUTC: 12,
      Battery: 'SD',
      Nro: 20,
    },
    GTIDF: {
      Evento: 3,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 7,
      Heading: 8,
      Altitud: 9,
      Lon: 10,
      Lat: 11,
      GNSSUTC: 12,
      Battery: 'SD',
      Nro: 20,
    },
    GTIGL: {
      Evento: 1,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 5,
      Speed: 8,
      Heading: 9,
      Altitud: 10,
      Lon: 11,
      Lat: 12,
      GNSSUTC: 13,
      Battery: 'SD',
      Nro: 21,
    },
    GTTOW: {
      Evento: 14,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 5,
      Speed: 8,
      Heading: 9,
      Altitud: 10,
      Lon: 11,
      Lat: 12,
      GNSSUTC: 13,
      Battery: 'SD',
      Nro: 21,
    },
    GTHBM: {
      Evento: 4,
      IMEI: 2,
      UID: 3,
      HARSH: 5,
      ExternalPower: 'SD',
      Speed: 8,
      Heading: 9,
      Altitud: 10,
      Lon: 11,
      Lat: 12,
      GNSSUTC: 13,
      Battery: 'SD',
      Nro: 21,
    },
    GTRTL: {
      Evento: 1,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 5,
      Speed: 8,
      Heading: 9,
      Altitud: 10,
      Lon: 11,
      Lat: 12,
      GNSSUTC: 13,
      Battery: 'SD',
      Nro: 21,
    },
    GTIGN: {
      Evento: 9,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 6,
      Heading: 7,
      Altitud: 8,
      Lon: 9,
      Lat: 10,
      GNSSUTC: 11,
      Battery: 'SD',
      Nro: 20,
    },
    GTIGF: {
      Evento: 10,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 6,
      Heading: 7,
      Altitud: 8,
      Lon: 9,
      Lat: 10,
      GNSSUTC: 11,
      Battery: 'SD',
      Nro: 20,
    },
    GTMPF: {
      Evento: 11,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 5,
      Heading: 6,
      Altitud: 7,
      Lon: 8,
      Lat: 9,
      GNSSUTC: 10,
      Battery: 'SD',
      Nro: 17,
    },
    GTMPN: {
      Evento: 12,
      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 5,
      Heading: 6,
      Altitud: 7,
      Lon: 8,
      Lat: 9,
      GNSSUTC: 10,
      Battery: 'SD',
      Nro: 17,
    },
    GTSTC: {
      Evento: 13,

      IMEI: 2,
      UID: 3,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 6,
      Heading: 7,
      Altitud: 8,
      Lon: 9,
      Lat: 10,
      GNSSUTC: 11,
      Battery: 'SD',
      Nro: 18,
    },
    GTSTT: {
      Evento: 1,
      IMEI: 2,
      UID: 3,
      Motion: 4,
      ExternalPower: 'SD',
      ReportID: 'SD',
      Speed: 6,
      Heading: 7,
      Altitud: 8,
      Lon: 9,
      Lat: 10,
      GNSSUTC: 11,
      Battery: 'SD',
      Nro: 18,
    },
    GTINF: {
      Nro: 25,
    },
    GTEPS: {
      Evento: 1,
      IMEI: 2,
      UID: 3,
      ExternalPower: 4,
      ReportID: 'SD',
      Speed: 8,
      Heading: 9,
      Altitud: 10,
      Lon: 11,
      Lat: 12,
      GNSSUTC: 13,
      Battery: 'SD',
      Nro: 21,
    },
    GTPNA: {
      Evento: 20,
      IMEI: 2,
      UID: 3,
      GNSSUTC: 4,
      Nro: 5,
    },
    GTPFA: {
      Evento: 21,
      IMEI: 2,
      UID: 3,
      GNSSUTC: 4,
      Nro: 5,
    },
  },
}

module.exports = config
